IRONDESK/moss

client/src/components/Join/FileUpload.tsx, client/src/components/Join/Join.tsx, client/src/constants/index.tsx
- 프로필 이미지 업로드 부분 에러를 해결했습니다.
- file의 타입을 blob으로 명시해주었습니다.
- 회원가입 페이지를 리팩토링했습니다.
- 회원가입 페이지 반응형은 헤더와 푸터를 제외하고 변경되는 게 없어 일단 max-with만 추가해놓은 상태입니다.
=> 🐛 프로필 이미지 업로드 에러 해결 및 리팩토링

client/src/components/SearchInput.tsx, client/src/components/TitleSearch.tsx, client/src/components/layouts/Layout.tsx, client/src/components/layouts/partials/Footer.tsx, client/src/components/layouts/partials/Header.tsx, client/src/pages/index.tsx
Header, Footer, Home 반응형 스타일 추가 
`@media (max-width: 440px)`에 맞춰 반응형 스타일 추가 했습니다.
피그마 UI에 따른 디자인 변경했습니다.
=> Header, Footer, Home 반응형 스타일 추가

client/src/components/StudyMain/Record.tsx, client/src/components/StudyMain/StudyTimer.tsx
- 타이머 기능 구현 (useState, setTimeout 등 Hook 사용)
- 목표 설정하는 UI 추가 구현
=> :sparkles: 타이머 기능 구현

client/src/pages/study/index.tsx, client/src/pages/study/notice/index.tsx, client/src/pages/study/notice/view.tsx, client/src/pages/study/notice/write.tsx, client/yarn.lock
=> :truck: 공지사항 라우팅 위치 변경

prisma/schema.prisma, src/components/StudyMain/Todo.tsx, src/pages/api/todoList/todo.tsx
- schema model 및 api 추가
- schema todo model을 추가했습니다.
- todo api를 추가했습니다.
- 아직 오류사항이 많습니다. 추후에 수정하겠습니다.
=> ✨  schema 업데이트 및 Todo api 추가

prisma/schema.prisma, src/components/MyPage/MyPageContainer.tsx, src/components/MyPage/StudyButton.tsx, src/pages/api/study/create.tsx, src/pages/my-page/index.tsx
- 마이페이지 UI 수정
- 스터디 신청 Modal 코드 리팩토링
=> :recycle: 마이페이지, 스터디 신청 Modal Frontend 코드 리팩토링

prisma/schema.prisma, src/pages/api/study/create.tsx
- StudyInfo 스키마 수정 (오류 발생하는 leader 우선 제거)
- api/study/create 수정
=> :recycle: studyinfo 스키마 수정, api 수정

src/components/StudyMain/StudyBanner.tsx, src/pages/api/study/create.tsx, src/pages/api/study/getInfo.tsx, src/pages/api/todo/todo.tsx, src/pages/study.tsx, src/pages/study/[studyId].tsx
- Study 정보 가져오는 API 구현
- Study 동적 라우팅 페이지 구현
- todo 충돌된 부분 수정
- StudyBanner 스타일링 일부 수정, 리팩토링
=> ✨ studyinfo get api 구현, dynamic routes 페이지 구현 등

prisma/schema.prisma, src/components/StudyCard.tsx, src/components/StudyList.tsx, src/components/StudyMain/StudyBanner.tsx, src/pages/api/study/create.tsx, src/pages/api/study/getInfo.tsx, src/pages/study/[studyId].tsx, src/pages/study/index.tsx
-  getInfo에서 SWR 사용하여 리팩토링
- StudyList 컴포넌트에 back 데이터 가져와 구현
- ``Studyinfo`` 스키마에 ``joinMember`` 속성 추가
=> ♻️ SWR 사용, 스터디 리스트 back 구현 등

src/components/Login/components/LoginForm.tsx, src/pages/api/users/join.ts, src/pages/join copy.tsx, src/pages/join.tsx, src/pages/profile/[id]/edit.tsx, src/pages/profile/[id]/index.tsx, src/styles/componentsStyles.ts, src/types/editProfile.ts, src/types/join.ts
회원가입 유효성 검사
회원가입시 각 항목에 대한 유효성 검사를 실시합니다.
* 아이디는 기호를 제외한 영문자 또는 6~20자리 숫자를 포함해야합니다.
* 비밀번호의 길이는 최소 8자리에서 최대 16자리이며 최소 1개이상의 숫자, 문자, 정의된 특수문자를 포함해야 합니다.
* 모든 오류메시지를 UI에 표시합니다.
* 비밀번호와 재확인 비밃번호의 일치여부를 백엔드와 프론트엔드 두곳에서 실행합니다.
* Unique값을 갖는 항목 (아이디, 이메일, 휴대폰번호)의 중복체크를 백엔드에서 검사합니다.
* 회원가입이 완료되면 메시지를 UI에 표시합니다.
(궁금한 사항들, 느낀 점 자유롭게 작성)
=> 회원가입 유효성 검사

prisma/schema.prisma, src/components/StudyMain/Container.tsx, src/components/StudyMain/Todo.tsx, src/components/StudyMain/TodoItem.tsx, src/pages/api/todo/delTodo.ts, src/pages/api/todo/editTodo.ts, src/pages/api/todo/index.ts, src/types/Todo.ts
- todo 스키마를 업데이트했습니다.
- todo 스키마를 studyId와 연결했습니다.
- study와 mypage ui를 구분할 수 있게 todo 컴포넌트를 수정했습니다.
- 마이 페이지
- 스터디 페이지
- studyId를 통해 study 정보를 가져오고 싶습니다. props로 전달하는 방법 밖에 없을까요.
- mutate 사용법을 알고 싶습니다.
=> ♻️ todo 스키마 수정 및 컴포넌트 리팩토링

prisma/schema.prisma, src/components/StudyMain/Container.tsx, src/components/StudyMain/Notice.tsx, src/pages/api/notice/index.ts, src/pages/api/notice/view.ts, src/pages/study/[studyId]/index.tsx, src/pages/study/[studyId]/notice/[id].tsx, src/pages/study/[studyId]/notice/edit/[id].tsx, src/pages/study/[studyId]/notice/index.tsx, src/pages/study/[studyId]/notice/write.tsx
- notice 스키마 변경
- 폴더 트리 변경
- notice 스키마 변경
-  user 포함
- study 포함
- 폴더 트리 변경
- study/[studyId]/notice
(궁금한 사항들, 느낀 점 자유롭게 작성)
=> :recycle: notice-스키마 수정

prisma/schema.prisma
=> :recycle: schema 괄호 누락 수정

src/components/Join/components/JoinInput.tsx, src/components/Login/LoginStart.tsx, src/components/Login/components/LoginForm.tsx, src/components/Login/components/LoginInput.tsx, src/components/Login/components/LoginLink.tsx, src/components/MyPage/MyPageBanner.tsx, src/components/MyPage/StudyList.tsx, src/pages/join/index.tsx, src/pages/my-page/index.tsx, src/styles/components.ts
- UI 및 마크업 수정
- 스터디페이지 UI 깨짐 CSS 수정
- 마크업개선 : label 추가
- 아이디,비밀번호 찾기 주석처리
- input 입력 폰트 색 변경
- 마크업 조금 심각하여 사실 어디서부터 어떻게 손을 대야할지 조금 막막합니다.😱
- 일단 지금 현재 데이터가 누락되거나 나오지 않는 부분이 있어서 마크업이 깨진것인지, 추후 진행되면서 수정해야할 것 같습니다!
- 일단 개발이 많이 진행되어서 최대한 개발코드를 수정하지 않는 선에서 수정작업 할 수 있도록 하겠습니다.
=> UI 및 마크업 수정

prisma/schema.prisma, src/components/MyPage/MyPageBanner.tsx, src/components/MyPage/MyStudyChart.tsx, src/components/MyPage/Record.tsx, src/components/MyPage/StudyTimer.tsx, src/pages/api/goal/index.ts
- goal-api 수정
- 목표량 배너 반영
- 출석 버튼 추가
- goal-api user 넣어서 수정했습니다.
- 목표량 배너에 출석일, 이제까지 공부시간에 보여지게 반영 했습니다.
-  출석버튼 추가 해서 출석일 카운트 되도록 했습니다
- 출석하면 alert뜨게 했습니다. 
- alert가 안뜨면 출석버튼이 눌렸는지 체크가 안되서 넣었는데, 좀 더 이쁘게 만들어도 좋을거 같아요.
- 몇월 공부시간 뜨는 부분은 우선은 updatedData의 month값을 가져왔는데, 어떤 식으로 새로고침 되면 좋을지 이야기 해봐야 할거같아요!
=> :sparkles: 목표량 구현

prisma/schema.prisma, src/components/StudyMain/Todo.tsx, src/components/StudyMain/TodoItem.tsx, src/pages/api/todo/index.ts, src/types/Todo.ts
- todo 리스트 마무리(아마도...)
- todo 스키마, api, 컴포넌트를 수정했습니다.
- 마이페이지 투두리스트에 각 스터디 태그를 분류했습니다.
=> ♻️ todo 리스트 리팩토링 및 태그 분류

src/components/MyPage/MyStudyChart.tsx, src/components/MyPage/StudyTimer.tsx, src/pages/api/goal/index.ts
-  my-page 오류 수정
- 공부 시간 없을때 NaN 뜨는 부분 수정
- 출석일 없을때 NaN 뜨는 부분 수정
- goal api 수정
(궁금한 사항들, 느낀 점 자유롭게 작성)
=> :bug: goal NaN 오류 수정

prisma/schema.prisma, src/components/MyPage/MyStudyChart.tsx, src/components/MyPage/StudyTimer.tsx, src/pages/api/goal/index.ts
- goal 스키마 변경
- NaN 오류 해결
- db 업데이트 문제 해결
- db가 업데이트 되지 않고, 생성되는 문제 해결
- NaN으로 뜨는 것들 기본값 0으로 변경 했습니다.
(궁금한 사항들, 느낀 점 자유롭게 작성)
=> :bug: goal 오류 수정

prisma/schema.prisma, src/components/MyPage/CreateStudy.tsx, src/components/StudyMain/ApplyStudyModal.tsx, src/components/StudyMain/Member.tsx, src/components/StudyMain/StudyBanner.tsx, src/components/StudyMain/StudyComponents.tsx, src/pages/api/study/[id]/index.ts, src/pages/api/study/apply.tsx, src/pages/api/study/create.ts, src/types/study.ts
- ``Study`` 스키마 수정 (joinMsg => welcome, joinMember => memberlist)
- Study 생성 API (``api/study/apply.tsx``)의 ``req.body``에 누락된 항목 추가
- StudyBanner, StudyComponents에 스키마 수정 내용 반영
=> :recycle: 스터디 신청 구현 수정, Study 스키마 수정

prisma/schema.prisma, src/components/StudyMain/Todo.tsx, src/pages/api/todo/index.ts, src/types/Todo.ts
=> ♻️ todo 최종

src/components/StudyCard.tsx, src/components/StudyList.tsx, src/components/StudyMain/StudyComponents.tsx
- 가입 스터디 블러 처리 보이지 않도록 수정
- StudyCard에서 스터디원 수 보이도록 구현 수정
=> ♻️ 스터디 가입 여부에 따른 blur 처리 기능, StudyCard 수정

README.md
-리드미 완성
- 리드미 완성
- 위키 완성
- 혹시 내용 수정 필요하신 분들은 말씀해주세요
=> :memo: readme 추가

src/components/StudyMain/StudyBanner.tsx, src/components/StudyMain/StudyComponents.tsx
- useUser state 반영되지 않아, 스터디 가입 여부 확인 되지 않는 문제 해결
(스터디 신청 버튼, 스터디 화면 블러 처리 문제 수정)
=> :recycle: 스터디 가입 여부 확인 되도록 수정

src/components/MyPage/MyStudyChart.tsx, src/components/MyPage/UserInfo.tsx, src/components/StudyMain/Member.tsx, src/components/StudyMain/TodoItem.tsx, src/components/layouts/partials/Footer.tsx, src/pages/api/todo/index.ts, src/styles/components.ts, src/styles/components/Calendar.ts
- 약간의 UI 수정(미디어쿼리)
- 모바일에서 깨지는 부분 UI 수정
- main 브랜치 제외하고 다른 브랜치에서는 todo 기능이 정상적으로 동작됩니다. 
- main 브랜치 제외하고 다른 브랜치에서는 todo 기능이 정상적으로 동작됩니다.
- 투두 스키마에서 @@index studyId를 지워주시면 감사하겠습니다.
=> ♻️ todo 및 UI 리팩토링
